version: '3.8'
services:
  backend:
    container_name: mks-mrp-be
    build:
      dockerfile: Dockerfile
    image: mks-mrp-be
    restart: always
    ports:
      - '8313:8313'
    volumes:
      - /home/ubuntu/mrp-mks/uploads:/mrp-mks/uploads
